export { default as Business } from './Business'
export { default as CTA } from './CTA'
export { default as Hero } from './Hero'
export { default as PriceList } from './PriceList'
export { default as Stats } from './Stats'
export { default as Testimonials } from './Testimonials'